### ISSUE TITLE
Obfuscate tokens in ELK and the log browser

### ISSUE THREAD

**Issue by christtyk** [TykTechnologies/tyk-pump#198]
From SLA Client: 

enable_key_logging in gateway config is set to false but doesn't obfuscate the keys in dashboard/ELK. 

They would like a solution to obfuscate these tokens in the dashboard.

**Comment by christtyk** [comment]
not stale

**Comment by letzya** [comment]
similar https://github.com/TykTechnologies/tyk-pump/pull/140

**Comment by tbuchaillot** [comment]
@letzya  #309 should close this right?

**Comment by letzya** [comment]
In which field do you see these keys? APIKey?

**Comment by gregdelhon** [comment]
@christtyk do you know or can check with the client? Pump 1.5 should help them.

**Comment by christtyk** [comment]
@gregdelhon can you point me to any relevant docs? I found the client so can pass on

**Comment by gregdelhon** [comment]
Ok my bad, misunderstanding here because I thought it was merged. It was then reverted here https://github.com/TykTechnologies/tyk-pump/pull/315 

The conclusion was that we needed to do it at GW level to make this right. I think this ticket is the one for this if you want to add it to your boards. https://tyktech.atlassian.net/browse/TT-1886 

Closing this to avoid further confusion.
