### ISSUE TITLE
Make the tyk_analytics collection capacity configurable in pump.conf

### ISSUE THREAD

**Issue by kohrVid** [TykTechnologies/tyk-pump#26]
At present, the `tyk_analytics` collection in MongoDB can grow until it hits the in-memory limit. This occurs because the Pump does not apply a cap on the size of the collection, nor does it apply any indexing.
The capacity applied will vary from each installation to another, based on the amount of RAM installed on the machine. A new feature should be added to make the capacity configurable from within the `pump.conf` file.

**Comment by buger** [comment]
Worth noticing that it should be compatible with previous installations. So basic logic is:
```js
if (!db['tyk_analytics.stats']()['is_capped']) {
  db.runCommand( { convertToCapped: 'tyk-analytics', size: <configurable size> } )
}
```
But just running it probably not a good idea, probably make sense add special option like `"convert_to_capped": true`. For new users it will do nothing, for old allow them to make conversion on their own terms. 

And I still believe that adding index to `timestamp` column is a good idea, because querying mongo with `sort` without index, considered harmful.

**Comment by lonelycode** [comment]
Also, the feature itself must be "enableable", i.e. if thje configurable value is 0 (default) then don;t cap it.

**Comment by buger** [comment]
Right, and it should handle changing capped value size, including edge cases.
So for example, if your collection was capped, and we set value back to 0, it should re-create `tyk-analytics` collection, with copying data to temporary table:
```
db.collection.copyTo("collection_temp")
db.collection.drop()
db.collection_temp.renameCollection("collection")
```

If config capped size != existing size it should update size, by calling `convertToCapped` with new size. 

And if nothing is changed, it should call nothing as well.

**Comment by nickReyn** [comment]
@MangoMM what's the status of this please?

**Comment by MangoMM** [comment]
@nickReyn currently in progress. https://github.com/TykTechnologies/tyk-pump/pull/50

**Comment by lonelycode** [comment]
We can release this at any time, so this does not need to be part of the v2.4 release block.
