### ISSUE TITLE
Mongo Pump forever connect loop

### ISSUE THREAD

**Issue by asoorm** [TykTechnologies/tyk-pump#48]
The mongo pump continually tries to reconnect with a 5 second sleep.

https://github.com/TykTechnologies/tyk-pump/blob/master/pumps/mongo.go#L123

An exponential backoff would be more appropriate and/or given a sensible number of retries or time, the pump should exit with a non-zero exit code.

It would then be the responsibility of the OS to restart on failure / restart always or not restart at all etc dependent on the user's own config.

**Comment by lonelycode** [comment]
This is a good idea, do you have a proposal for how that exponential backoff should work, and it should it be the individual pumps responsibility to handle it or should it be an interface?

**Comment by MangoMM** [comment]
You've got me thinking... The exponential backoff algorithm could take some kind of operation function as one of it's arguments. The operation would return success or failure and the retry logic would happen within the algorithm. In case of mongo pump - the connect logic would wrapped by the operation function.

Doing the way above would mean that anytime we want some kind of expo backoff retry logic, we can reuse the algorithm. Also, it means that for things like the CSV pump, we wouldn't need to implement as it doesn't apply.

Just a rough idea:
```
interface ExponentialBackoff(operation func, config Config) {}

type Config struct {
    InitialDelay                    time.Millisecond
    EnableRandomJitter    bool // Stops multiple retries from multiple processes happening at same time
    MultiplicationFactor    float32
    Interval                         time.Duration
    MaxRetries                   uint
}
```

As a side note, does mongo not have some kind of heartbeat to ensure that the connection is alive? Because it seems like we are constantly checking and reconnecting.

**Comment by lonelycode** [comment]
So wrapping the connection function in a closure and passing it to a backoff algo? Sounds complicated and assumes that it's going to be used.

But you'll need a shared backoff for the two Mongo Pumps at minimum so you might as well implement it in a bare bones way so it works with those.

It could always be a utility package that the pump can import, settings should be provided per pump.

I'd not over-generalise too much and focused on KISS.
