### ISSUE TITLE
bug: WriteUptimeData best-effort insert logic potential data loss

### ISSUE THREAD

**Issue by asoorm** [TykTechnologies/tyk-pump#49]
WriteUptimeData attempts to insert into the AnalyticsCollection. Upon failure an error log is written and if due to disconnect, attempts reconnect. WriteUptimeData doesn't currently return anything.

https://github.com/TykTechnologies/tyk-pump/blob/master/pumps/mongo.go#L267

The problem with this logic is that because the caller `StartPurgeLoop` does not get feedback from `WriteUptimeData` as to whether the operation was successful or not. WriteUptimeData does not return anything. As such, data becomes purged from the analytics storage despite not having been successfully written to Mongo.

Is it intended functionality for `WriteUptimeData` to be on a best-effort basis and a degree of data loss acceptable for this logic?

**Comment by lonelycode** [comment]
At the moment it is best-effort basis, otherwise in a high traffic environment the pump might just fill up with old data and fall over, losing the data anyway. There's a flip-side to this: if the pump dies then redis fills up, so we actually also need a sensible TTL or max-size of the data storable in redis to avoid a bottleneck there.
