### ISSUE TITLE
Request for integration with AWS Event Bridge for log shipping

### ISSUE THREAD

**Issue by razie69** [TykTechnologies/tyk-pump#737]
We are interested in integrating tyk-pump with event bridge for our company requirements and also we are willing to take responsibility for developing the integration. To move forward, We would like to discuss with you about the ways to do it. Would it be a fine integration with sqs/sns features or the event bridge itself, or any other reasonable AWS services.
How do you plan to implement this integration if you have initial thoughts.

We are excited about potential of this integration and look forward to your guidance and collaboration.
Thank you

**Comment by SonjaChevre** [comment]
Hey @razie69, 

thank you for reaching out! can you tell us a bit more about your use case, what is the end observability tools where you are going to store the logs? 

Also have you looked if OpenTelemetry can help you solve this without needing integration work? 

We just shipped our first integration with OpenTelemetry distributed tracing: https://tyk.io/docs/product-stack/tyk-gateway/advanced-configurations/distributed-tracing/open-telemetry/open-telemetry-overview/ and we are eagerly collecting feedback. 

The OpenTelemetry collector offers lots of options to convert your data to different systems using exporters also to AWS services (https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/exporter) and AWS is a strong contributor to OpenTelemetry as well: https://aws.amazon.com/otel/. 

Generally speaking, because of OpenTelemetry strong adoption, we prefer to go the OpenTelemetry way than to add support for new vendors/formats and having to maintain those integration in the future.

Looking forward to hear back from you!
Sonja

**Comment by razie69** [comment]
Hey SonjaChevre, 
Thanks for following up.

Actually our use case is beyond observability and we are going to have some business related use cases for the incoming access logs.
we need to pump our access logs into a queue system and later consume on that.
we are looking for AWS managed services like SQS or SNS
our MR would be sth like adding Kafka support.
 
TYK <=> TYK Pump <=> SQS <=> Internal consumers processing business related logics

If you need more information to consider, please let us know.
Thanks in advance.

**Comment by masoudhaghbin** [comment]
Hi
I wanted to know when will the 1.9 be released?
@mativm02 
Thanks

**Comment by caroltyk** [comment]
Hello @masoudhaghbin , we are at the final stage of testing. Please expect it to be ready in coming weeks! Thanks for being patience with us.

**Comment by caroltyk** [comment]
A little belated update on this - Thank you for your contribution to Pump ❤️ v1.9 has been released on 5 Apr.
